name: Task 04
run-name: Mirroring Repository
on: [push]
jobs:
  mirror_repository:
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Flavio-KOUGBADI/Dump.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY}}
