name: Test n¹
run-name: Execute some commands as tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "================================"
      - run: ls -la
      - run: echo "================================"
